## Numpy Quiz1

In [2]:
import numpy as np

Q1. arange(), reshape() 이용 1차원 2차원 3차원 배열 생성

In [91]:
arr1d = np.arange(12).reshape(-1,)
arr2d = np.arange(12).reshape(2,6)
arr3d = np.arange(24).reshape(2,4,3)

print(arr1d, arr1d.shape)
print(arr2d, arr2d.shape)
print(arr3d, arr3d.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] (2, 6)
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]] (2, 4, 3)


Q2. reshape(-1,-1)을 이용 1차원을 2차원, 3차원으로 2차원을 1차원 3차원으로 3차원을 1차원 2차원으로 변환

In [93]:
arr1d2 = arr1d.reshape(2, -1)
print(arr1d2)
arr1d3 = arr1d.reshape(3,2, -1)
print(arr1d3)
print()

arr2d1 = arr2d.reshape(-1)
print(arr2d1)
arr2d3 = arr2d.reshape(2, 2, -1)
print(arr2d3)
print()

arr3d1 = arr3d.reshape(-1)
print(arr3d1)
arr3d2 = arr3d.reshape(4, -1)
print(arr3d2)
print()

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]



Q3. Q1 1차원 배열을 실수형으로 변환

In [37]:
arr1d = arr1d.astype(float)
print(arr1d, arr1d.dtype)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.] float64


Q4. Q1 1차원 배열의 dtype을 확인

In [ ]:
print(arr1d, arr1d.dtype)

Q5. 주어진 배열에서 음수 값을 모두 0으로 변경하세요.

arr = np.array([-5, -3, -1, 0, 1, 3, 5])

In [38]:
arr = np.array([-5, -3, -1, 0, 1, 3, 5])

arr[arr < 0] = 0
np.where(arr < 0, 0, arr)
print(arr)

[0 0 0 0 1 3 5]


Q6. 1 ~ 100 까지 배열에서 3의 배수인 것만을 출력

In [41]:
arr = np.arange(1,101)
arr[(arr % 3) ==0]

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

Q7. 1 ~ 100 까지 배열에서 5의 배수이면서 2의 배수인 것만을 출력

In [42]:
arr = np.arange(1,101)
arr[(arr % 10) == 0]

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

Q8. 1 ~ 100 까지 배열에서 3의 배수이거나 5의 배수인 것만을 출력

In [50]:
arr = np.arange(1,101)
arr[((arr % 3) == 0) | ((arr % 5) == 0)]

array([  3,   5,   6,   9,  10,  12,  15,  18,  20,  21,  24,  25,  27,
        30,  33,  35,  36,  39,  40,  42,  45,  48,  50,  51,  54,  55,
        57,  60,  63,  65,  66,  69,  70,  72,  75,  78,  80,  81,  84,
        85,  87,  90,  93,  95,  96,  99, 100])

Q9. 101 ~ 150 사이의 정수를 랜덤하게 추출, 2행 5열 다차원 배열을 생성 후 전치하세요

In [53]:
arr = np.random.randint(101, 151, size=(2,5))
arr.T

array([[117, 122],
       [142, 131],
       [147, 107],
       [145, 131],
       [141, 150]])

Q10. 표준정규분포로 구성된 5행 5열 다차원 배열을 생성하세요.

In [54]:
arr = np.random.randn(5,5)
arr

array([[-0.9831788 ,  0.32856444, -0.59780972, -0.47218604,  0.98327867],
       [ 0.2342678 ,  2.21285747,  0.76654211, -1.24470456,  0.13396354],
       [-0.3979788 ,  0.05108151, -1.59023141, -0.88512206, -0.48218516],
       [ 1.26230162,  0.22851433,  0.39997803,  0.71623249,  1.27130231],
       [-0.92148264,  0.10542718, -0.77531022,  2.04993308, -0.99939992]])

Q11. original_array를 1차원 배열로 변환하여 출력하세요.

In [55]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])
flattened_arr = original_array.flatten()
print(faltened_arr)
arr1d = original_array.reshape(-1)
arr1d

array([1, 2, 3, 4, 5, 6])

Q12. 주어진 2차원 배열에서 첫 번째 행을 view로 생성하고, 이 view를 수정하여 원본 배열에 반영되도록 하세요.

original_array = np.array([[1, 2, 3], [4, 5, 6]])

In [102]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])

arr = original_array[0,:]
arr[:] = 10

print(original_array)

[[10 10 10]
 [ 4  5  6]]


Q13. 주어진 3차원 배열에서 첫 번째 2차원 배열을 view로 생성하고, 이 view를 수정하여 원본 배열에 반영되도록 하세요.

original_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [59]:
original_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

arr2d = original_array[0]
print(arr2d, '\n')

arr2d[0] = 10
print(original_array)

[[1 2 3]
 [4 5 6]] 

[[[10 10 10]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Q14. 주어진 2차원 배열을 1차원 배열 view로 reshape하고, 이 view를 수정하여 원본 배열에 반영되도록 하세요.

original_array = np.array([[1, 2, 3], [4, 5, 6]])

In [60]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])

arr1d = original_array.reshape(-1)
arr1d[0] = 10

print(original_array)

[[10  2  3]
 [ 4  5  6]]


Q15. np.ones((10,10))을 아래와 같이 출력하세요.
```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
 ```

In [103]:
arr = np.ones((10,10))
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Q16. Q. 1 ~ 100을 아래와 같이 출력하세요.

```
[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]]
 ```

In [107]:
arr = np.arange(1,101).reshape(10,10)
ar = []
for i in range(10):
  idx = arr[i]
  if i % 2 == 0:
    idx[i] = idx[i][::-1]
    ar.append(idx[i])
  else:
    idx[i] = idx[i]
    ar.append(idx[i])


IndexError: invalid index to scalar variable.

Q17. np.ones((5,5))을 아래와 같이 출력하세요.
```
      [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]]
```

In [108]:
arr = np.zeros((9,9))
arr[2:7, 2:7] = 1

print(arr)

np.pad(arr, pad_width=1, mode='constant', constant_values=0)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Q18. np.arange(4)을 이용해서 아래와 같이 출력하세요.
```
[[0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 2, 0, 0, 0],
 [0, 0, 3, 0, 0],
 [0, 0, 0, 4, 0]]
```

In [109]:
arr = np.zeros((5,5))
a = [1,2,3,4]
arr[1,0] = 1
arr[2,1] = 2
arr[3,2] = 3
arr[4,3] = 4
print(arr)

np.diag(1+np.arange(4), k=-1) # diag : 대각선. -1은 밑으로 +1은 위로

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

Q19. Q. np.zeros((8,8))을 이용해서 아래와 같이 출력하세요(두가지 방식:인덱싱, tile 함수)
```
[[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0]]
```

In [113]:
arr = np.zeros((8,8), dtype=int)
arr[0::2, 1::2] = 1
arr[1::2, ::2] = 1
print(arr)

arr = np.tile([[0,1],[1,0]], (4,4))
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Q20. np.arange(336).reshape(6,7,8)에서 100번째 요소의 인덱스를 구하세요.

In [112]:
arr = np.arange(336).reshape(6,7,8)

index_100 = np.unravel_index(99, arr.shape)
print(index_100)

(1, 5, 3)
