In [2]:
import numpy as np

Task1_0611. 주어진 대각 행렬의 역행렬을 구하고, 역행렬이 맞는지 확인하세요.

D = np.diag([1, 2, 3])

In [4]:
D = np.diag([1, 2, 3])

print(np.linalg.inv(D))

# 곱했을 때 단위행렬이 되면 역행렬
print(D.dot(np.linalg.inv(D)))
print(D @ np.linalg.inv(D))

[[1.         0.         0.        ]
 [0.         0.5        0.        ]
 [0.         0.         0.33333333]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Task2_0611. 임의의 상삼각 행렬을 생성하고, 그 행렬로 부터 하삼각 행렬을 구하여 출력하세요.

In [8]:
arr = np.random.randint(1,10,size=(3,3))

# 상삼각 행렬 생성
uarr = np.triu(arr)

# 하삼각 행렬
larr = np.tril(arr)
np.tril(uarr)

array([[7, 0, 0],
       [0, 4, 0],
       [0, 0, 3]])

Task3_0611. 주어진 행렬의 역행렬을 구하고, 역행렬이 맞는지 확인하세요.

A = np.array([[4, 7], [2, 6]])

In [11]:
A = np.array([[4, 7], [2, 6]])

np.linalg.inv(A)

A @ np.linalg.inv(A) # 단위행렬일시 역행렬

np.linalg.det(A) # 행렬식이 0이면 역행렬 X

10.000000000000002

Task4_0611. 주어진 데이터 포인트와 모델 파라미터를 사용하여 선형 회귀 모델의 예측값을 계산하세요.

X = np.array([1, 2, 3])

- 1단계 : 주어진 입력 데이터 포인트 X와 모델 파라미터 θ를 정의.
- 2단계 : 행렬 곱을 사용하여 예측값 y를 계산.

In [12]:
# 데이터 포인트 X와 모델 파라미터 델타 정의
X = np.array([1,2,3])
W = np.array([2,4,6])

# 행렬 곱을 사용하여 예측값 y 계산
y = X @ W
print(y)

28


Task5_0611. 주어진 입력 벡터와 가중치 행렬을 사용하여 신경망의 단일 계층 출력을 계산하세요.

- 1단계: 입력 벡터 X와 가중치 행렬 W를 정의.
- 2단계: 행렬 곱을 사용하여 계층의 출력을 계산.

In [16]:
# 입력 벡터 X와 가중치 행렬 W 정의
X = np.array([1,2,3])
W = np.array([[1,2,3], [5,6,7]])

# 행렬 곱을 사용하여 계층의 출력 계산


ValueError: shapes (3,) and (2,3) not aligned: 3 (dim 0) != 2 (dim 0)

Task6_0611. 주어진 입력 벡터에 대해 신경망의 활성화 함수(ReLU, 시그모이드)를 적용하여 출력을 계산하세요.

X = np.array([1, -2, 3])

- 1단계: 입력 벡터 X를 정의.
- 2단계: 가중치 행렬 W와 편향 벡터 b를 정의.
- 3단계: 활성화 함수(ReLU, 시그모이드)를 적용하여 출력을 계산
활성화 함수 적용<br>
output_relu = relu(Z)<br>
output_sigmoid = sigmoid(Z)

In [ ]:
X = np.array([0.5, 1.0, -1.5])

output_relu = relu(Z)
output_sigmoid = sigmoid(Z)

Task7_0611. 주어진 선형 방정식을 행렬 형태로 나타내고, 역행렬을 사용하여
x와 y를 구하세요.

$\begin{cases}
3x + 4y = 10 \\
2x + y = 5
\end{cases}$

단계:
1. 계수 행렬 A와 결과 벡터 b를 정의.
2. 행렬 A의 역행렬을 구한다.
3. 역행렬을 사용하여 변수 x를 구한다.

In [ ]:
a = np.array([[3]])

Task7_0611. 주어진 선형 방정식을 행렬 형태로 나타내고, 역행렬을 사용하여
x와 y를 구하세요.

$\begin{cases}
3x + 4y = 10 \\
2x + y = 5
\end{cases}$

단계:
1. 계수 행렬 A와 결과 벡터 b를 정의.
2. 행렬 A의 역행렬을 구한다.
3. 역행렬을 사용하여 변수 x를 구한다.

Task8_0611. 주어진 2D 평면의 점을 특정 변환 행렬을 사용하여 변환한 후, 변환된 좌표를 원래 좌표로 되돌리세요.

원래 점의 좌표 p와 변환 행렬 T 정의<br>
p = np.array([1, 2])<br>
T = np.array([[2, 0], [0, 3]])

단계
1. 원래 점의 좌표 p와 변환 행렬 T를 정의.
2. 변환 행렬 T를 사용하여 새로운 좌표 p를 계산.
3. 변환 행렬 T의 역행렬을 사용하여 새로운 좌표 p에서 원래 좌표 p를 복원.