In [ ]:
import numpy as np

Task1_0611. 주어진 대각 행렬의 역행렬을 구하고, 역행렬이 맞는지 확인하세요.

D = np.diag([1, 2, 3])

In [ ]:
D = np.diag([1, 2, 3])

print(np.linalg.inv(D))

# 곱했을 때 단위행렬이 되면 역행렬
print(D.dot(np.linalg.inv(D)))
print(D @ np.linalg.inv(D))

[[1.         0.         0.        ]
 [0.         0.5        0.        ]
 [0.         0.         0.33333333]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Task2_0611. 임의의 상삼각 행렬을 생성하고, 그 행렬로 부터 하삼각 행렬을 구하여 출력하세요.

In [ ]:
arr = np.random.randint(1,10,size=(3,3))

# 상삼각 행렬 생성
uarr = np.triu(arr)

# 하삼각 행렬
larr = uarr.T
larr

array([[9, 0, 0],
       [5, 3, 0],
       [9, 1, 8]])

Task3_0611. 주어진 행렬의 역행렬을 구하고, 역행렬이 맞는지 확인하세요.

A = np.array([[4, 7], [2, 6]])

In [ ]:
A = np.array([[4, 7], [2, 6]])

np.linalg.inv(A)

res = A @ np.linalg.inv(A) # 단위행렬일시 역행렬

np.linalg.det(A) # 행렬식이 0이면 역행렬 X

l = np.eye(2) # 단위행렬

np.allclose(res, l)

[[1. 0.]
 [0. 1.]]


True

Task4_0611. 주어진 데이터 포인트와 모델 파라미터를 사용하여 선형 회귀 모델의 예측값을 계산하세요.

X = np.array([1, 2, 3])

- 1단계 : 주어진 입력 데이터 포인트 X와 모델 파라미터 θ를 정의.
- 2단계 : 행렬 곱을 사용하여 예측값 y를 계산.

In [ ]:
# 데이터 포인트 X와 모델 파라미터 델타 정의
# 모델 파라미터 : 가중치 행렬
X = np.array([1,2,3])
W = np.array([0.5,1.5,-2])

# 행렬 곱을 사용하여 예측값 y 계산
y = X @ W
print(y)

-2.5


Task5_0611. 주어진 입력 벡터와 가중치 행렬을 사용하여 신경망의 단일 계층 출력을 계산하세요.

- 1단계: 입력 벡터 X와 가중치 행렬 W를 정의.
- 2단계: 행렬 곱을 사용하여 계층의 출력을 계산.

In [ ]:
# 입력 벡터 X와 가중치 행렬 W 정의
X = np.arange(3)
W = np.arange(6).reshape(3,2)

# 행렬 곱을 사용하여 계층의 출력 계산
# W는 가중치 행렬, X는 입력 벡터이고 일반적인 표기방식은 WX
Z = np.dot(X,W) # 가중치 우선, 그 다음이 입력벡터. 거꾸로 입력하면 안됨.
# 이때 W는 (3,3) X는 (1,3)이기 때문에 numpy가 자동으로 X를 전치하여 계산

print(Z)

(3,)
(3, 2)
[10 13]


Task6_0611. 주어진 입력 벡터에 대해 신경망의 활성화 함수(ReLU, 시그모이드)를 적용하여 출력을 계산하세요.

X = np.array([1, -2, 3])

- 1단계: 입력 벡터 X를 정의.
- 2단계: 가중치 행렬 W와 편향 벡터 b를 정의.
- 3단계: 활성화 함수(ReLU, 시그모이드)를 적용하여 출력을 계산
활성화 함수 적용<br>
output_relu = relu(Z)<br>
output_sigmoid = sigmoid(Z)

In [ ]:
def relu(z):
  return np.maximum(0, z)

def sigmoid(z):
  return 1 / (1 + np.exp(-z))

# 입력 벡터 X 정의
X = np.array([0.5, 1.0, -1.5])

# 가중치 행렬 W 정의
W = np.arange(6).reshape(3,2)

# 편향 벡터 b 정의
b = np.array([0.1, -0.2]) # 편향에는 스칼라, 벡터, 행렬이 있다.

Z = X @ W + b
#Z = np.dot(X,W) + b

res = relu(Z)
print(res)

[0. 0.]


Task7_0611. 주어진 선형 방정식을 행렬 형태로 나타내고, 역행렬을 사용하여
x와 y를 구하세요.

$\begin{cases}
3x + 4y = 10 \\
2x + y = 5
\end{cases}$

단계:
1. 계수 행렬 A와 결과 벡터 b를 정의.
2. 행렬 A의 역행렬을 구한다.
3. 역행렬을 사용하여 변수 x를 구한다.

[풀이]
주어진 선형방정식을 행렬 형태로 나타내면 다음과 같다: \\
$A\mathbf{x} = \mathbf{b}$ \\
여기서 \\
$A = \begin{bmatrix}3 & 4 \\2 & 1\end{bmatrix}$,

$\mathbf{x} = \begin{bmatrix}x \\y\end{bmatrix}$,

$\mathbf{b} = \begin{bmatrix}10 \\5\end{bmatrix}$

$\mathbf{x} = A^{-1} \mathbf{b}$

In [ ]:
# 계수행렬 : x와 y 앞에 있는 숫자들의 행렬. 위 방정식 모음과 밑 방정식 계수 모음을 따로 묶어야한다.
A = np.array([[3, 4], [2, 1]])
b = np.array([[10],[5]])

# A역행렬과 b를 행렬곱하면 변수 x가 나온다.
res = np.linalg.inv(A) @ b
print(res)

Task7_0611. 주어진 선형 방정식을 행렬 형태로 나타내고, 역행렬을 사용하여
x와 y를 구하세요.

$\begin{cases}
3x + 4y = 10 \\
2x + y = 5
\end{cases}$

단계:
1. 계수 행렬 A와 결과 벡터 b를 정의.
2. 행렬 A의 역행렬을 구한다.
3. 역행렬을 사용하여 변수 x를 구한다.

In [ ]:
A = np.array([[3, 4], [2, 1]])
b = np.array([[10], [5]])

Z = np.linalg.inv(A)
res = np.dot(Z,b)
print(res)

Task8_0611. 주어진 2D 평면의 점을 특정 변환 행렬을 사용하여 변환한 후, 변환된 좌표를 원래 좌표로 되돌리세요.

원래 점의 좌표 p와 변환 행렬 T 정의<br>
p = np.array([1, 2])<br>
T = np.array([[2, 0], [0, 3]])

단계
1. 원래 점의 좌표 p와 변환 행렬 T를 정의.
2. 변환 행렬 T를 사용하여 새로운 좌표 p'를 계산.
3. 변환 행렬 T의 역행렬을 사용하여 새로운 좌표 p'에서 원래 좌표 p를 복원.

In [ ]:
p = np.array([1, 2])
T = np.array([[2, 0], [0, 3]])

# 변환 행렬 T를 사용하여 새로운 좌표 p를 계산
p2 = np.dot(T,p) # 새로운 좌표 p'
T_inv = np.linalg.inv(T) # 변환행렬 T의 역행렬

# 원래 좌표 p 복원
p_restored = np.dot(T_inv, p2)

print("p : ", p)
print("p': ", p2)
print("p_restored : ", p_restored)

p :  [1 2]
p':  [2 6]
p_restored :  [1. 2.]
